import { Bot } from "../types/game";

export const BOTS: Bot[] = [
  {
    id: "chopper",
    name: "CHOPPER",
    avatar: "/bots/chopper.png",
    target: 2000,
    greed: 0.5,
    risk: 0.4,
    statue: "rumbleball",
  },
  {
    id: "ussop",
    name: "USSOP",
    avatar: "/bots/ussop.png",
    target: 2000,
    greed: 0.42,
    risk: 0.32,
    statue: "none",
  },
  {
    id: "buggy",
    name: "BUGGY",
    avatar: "/bots/buggy.png",
    target: 2000,
    greed: 0.55,
    risk: 0.62,
    statue: "none",
  },
  {
    id: "brook",
    name: "BROOK",
    avatar: "/bots/brook.png",
    target: 2000,
    greed: 0.48,
    risk: 0.46,
    statue: "none",
  },
  {
    id: "nami",
    name: "NAMI",
    avatar: "/bots/nami.png",
    target: 4000,
    greed: 0.63,
    risk: 0.38,
    statue: "none",
  },
  {
    id: "robin",
    name: "ROBIN",
    avatar: "/bots/robin.png",
    target: 4000,
    greed: 0.58,
    risk: 0.35,
    statue: "none",
  },
  {
    id: "law",
    name: "LAW",
    avatar: "/bots/law.png",
    target: 4000,
    greed: 0.57,
    risk: 0.52,
    statue: "none",
  },
  {
    id: "jinbe",
    name: "JINBE",
    avatar: "/bots/jinbe.png",
    target: 4000,
    greed: 0.54,
    risk: 0.44,
    statue: "none",
  },
  {
    id: "luffy",
    name: "LUFFY",
    avatar: "/bots/luffy.png",
    target: 4000,
    greed: 0.6,
    risk: 0.7,
    statue: "gomgumfruit",
  },
  {
    id: "sanji",
    name: "SANJI",
    avatar: "/bots/sanjihappy.png",
    target: 4000,
    greed: 0.61,
    risk: 0.55,
    statue: "none",
  },
  {
    id: "zoro",
    name: "ZORO",
    avatar: "/bots/zoro.png",
    target: 8000,
    greed: 0.72,
    risk: 0.58,
    statue: "none",
  },
  {
    id: "franky",
    name: "FRANKY",
    avatar: "/bots/franky.png",
    target: 8000,
    greed: 0.7,
    risk: 0.5,
    statue: "cola",
  },
  {
    id: "shanks",
    name: "SHANKS",
    avatar: "/bots/shanks.png",
    target: 8000,
    greed: 0.74,
    risk: 0.57,
    statue: "none",
  },
  {
    id: "teach",
    name: "TEACH",
    avatar: "/bots/teach.png",
    target: 8000,
    greed: 0.84,
    risk: 0.72,
    statue: "none",
  },
  {
    id: "bigmom",
    name: "BIG MOM",
    avatar: "/bots/bigmom.png",
    target: 8000,
    greed: 0.8,
    risk: 0.64,
    statue: "none",
  },
  {
    id: "imu",
    name: "IMU",
    avatar: "/bots/imu.png",
    target: 8000,
    greed: 0.8,
    risk: 0.6,
    statue: "cursemark",
  },
  {
    id: "nika",
    name: "NIKA",
    avatar: "/bots/nika.png",
    target: 8000,
    greed: 0.67,
    risk: 0.78,
    statue: "none",
  },
];